// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/LeMinh0706/lala-song/internal/db"
	"github.com/LeMinh0706/lala-song/internal/module/user"
	"github.com/LeMinh0706/lala-song/token"
)

// Injectors from user.wire.go:

func InitUserRouterHandler(q *db.Queries, token2 token.Maker) (*user.UserController, error) {
	iUserService := user.NewUserService(q)
	userController := user.NewUserController(iUserService, token2)
	return userController, nil
}
