// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Album struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	SingerID int64  `json:"singer_id"`
	ImageUrl string `json:"image_url"`
}

type Favorite struct {
	UserID uuid.UUID `json:"user_id"`
	SongID uuid.UUID `json:"song_id"`
}

type Genre struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	ImageUrl string `json:"image_url"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Singer struct {
	ID       int64  `json:"id"`
	Fullname string `json:"fullname"`
	ImageUrl string `json:"image_url"`
}

type SingerSong struct {
	SongID   uuid.UUID `json:"song_id"`
	SingerID int64     `json:"singer_id"`
}

type Song struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SongFile  string    `json:"song_file"`
	LyricFile string    `json:"lyric_file"`
	CreatedAt time.Time `json:"created_at"`
	AlbumID   int64     `json:"album_id"`
}

type SongGenre struct {
	GenresID int64     `json:"genres_id"`
	SongID   uuid.UUID `json:"song_id"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Fullname  string    `json:"fullname"`
	Gender    int32     `json:"gender"`
	Avt       string    `json:"avt"`
	RoleID    int32     `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}
