// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	Register(ctx context.Context, arg RegisterParams) (User, error)
}

var _ Querier = (*Queries)(nil)
