// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: singer.sql

package db

import (
	"context"
)

const createSinger = `-- name: CreateSinger :one
INSERT INTO singers (
    fullname,
    image_url
) VALUES (
    $1, $2
) RETURNING id, fullname, image_url, is_deleted
`

type CreateSingerParams struct {
	Fullname string `json:"fullname"`
	ImageUrl string `json:"image_url"`
}

func (q *Queries) CreateSinger(ctx context.Context, arg CreateSingerParams) (Singer, error) {
	row := q.db.QueryRowContext(ctx, createSinger, arg.Fullname, arg.ImageUrl)
	var i Singer
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.ImageUrl,
		&i.IsDeleted,
	)
	return i, err
}

const getSinger = `-- name: GetSinger :one
SELECT id, fullname, image_url, is_deleted FROM singers 
LIMIT $1 
OFFSET $2
`

type GetSingerParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetSinger(ctx context.Context, arg GetSingerParams) (Singer, error) {
	row := q.db.QueryRowContext(ctx, getSinger, arg.Limit, arg.Offset)
	var i Singer
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.ImageUrl,
		&i.IsDeleted,
	)
	return i, err
}
